- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present

- name: Ensure PostgreSQL is running
  systemd:
    name: postgresql
    state: started
    enabled: yes

- name: Create database
  postgresql_db:
    name: stanley_cup
    state: present

- name: Create chicago_blackhawks table
  shell: |
    sudo -u postgres psql -d stanley_cup -c "CREATE TABLE IF NOT EXISTS chicago_blackhawks (id SERIAL PRIMARY KEY, year INTEGER NOT NULL);"

- name: Insert 2010 into chicago_blackhawks table
  shell: |
    sudo -u postgres psql -d stanley_cup -c "INSERT INTO chicago_blackhawks (year) VALUES (2010);"
  ignore_errors: yes

- name: Insert 2013 into chicago_blackhawks table
  shell: |
    sudo -u postgres psql -d stanley_cup -c "INSERT INTO chicago_blackhawks (year) VALUES (2013);"
  ignore_errors: yes

- name: Insert 2015 into chicago_blackhawks table
  shell: |
    sudo -u postgres psql -d stanley_cup -c "INSERT INTO chicago_blackhawks (year) VALUES (2015);"
  ignore_errors: yes
